title: Uysim Ty | Independent Web Consulting
description: > # this means to ignore newlines until "baseurl:"
  Tips, best Practices and style guides for development. Keep sharing development experiences through this blog.


permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uysim.com" # the base hostname & protocol for your site, e.g. http://example.com


site-twitter: https://twitter.com/Uysim1 #if your site has a twitter account, enter it here

# Author Settings
author: Uysim Ty # add your name
author-img: avatar.jpg # add your photo
about-author: "Learning and Develop.\n Feedback and Improvement.\n Delivery with Quality."
social-img: 'social-image.jpg'
social-twitter: null # add your Twitter handle
social-facebook: uysim # add your Facebook handle
social-github: Uysim # add your Github handle
social-linkedin: uysim-ty # add your Linkedin handle
social-email: uysimty@gmail.com
social-upwork: https://www.upwork.com/o/profiles/users/_~019c06dd3d4065a0ac/

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-86820621-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
